# Generated by Django 4.0.3 on 2022-04-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_post_favourite_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
